### ISSUE TITLE
report-only and report_format not implemented ?

### ISSUE THREAD

**Issue by inkhey** [twu/skjold#11]
Hello,
Thanks for this program.
I do tried the report_only mode with report_format as json but cannot make it work, it seems the program just ignore it.
I check a bit into the code but i didn't found the part of the code that does make these parameter work, so i'm thinking that maybe an unimplemented feature ?

**Comment by twu** [comment]
Hej,

Thanks for giving `skjold` a shot :)

Where are you specifying `report_only` and `report_format`? There might be a bug/issue with how different configuration options are set/overridden depending on how the setup looks.

To answer your question. Yes, both `report_only` and `report_format` are implemented and should work. Here is a short example with a known vulnerable version of `urllib3` where we are specifying `-o json` for JSON output and `-r` for report-only.

```
echo "urllib3==1.23" | skjold audit -o json -r -s gemnasium -

[
  {
    "severity": "MEDIUM",
    "name": "urllib3",
    "version": "1.23",
    "versions": "<=1.24.2",
    "source": "gemnasium",
    "summary": "CRLF injection. In the urllib3 library for Python, CRLF injection is possible if the attacker controls the request parameter.",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2019-11236",
      "https://github.com/urllib3/urllib3/issues/1553",
      "https://bugs.python.org/issue36276",
      "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11236"
    ],
    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-11236"
  },
  {
    "severity": "HIGH",
    "name": "urllib3",
    "version": "1.23",
    "versions": "<1.24.2",
    "source": "gemnasium",
    "summary": "Weak Authentication Caused By Improper Certificate Validation. The urllib3 library for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the `ssl_context`, `ca_certs`, or `ca_certs_dir` argument.",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2019-11324",
      "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11324",
      "https://www.openwall.com/lists/oss-security/2019/04/19/1"
    ],
    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-11324"
  },
  {
    "severity": "MEDIUM",
    "name": "urllib3",
    "version": "1.23",
    "versions": "<1.25.9",
    "source": "gemnasium",
    "summary": "Injection Vulnerability. urllib3 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting `CR` and `LF` control characters in the first argument of `putrequest()`. NOTE: this is similar to CVE-2020-26116.",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2020-26137",
      "https://bugs.python.org/issue39603"
    ],
    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-26137"
  }
]
```

Since we specified `-r`/`--report-only` `skjold` should have returned with a exit code `0`. 

```
echo $?

0
```

Which it did. You can replace `skjold audit -o json -r -s gemnasium -` with i.e. `skjold audit -o json -r -s gemnasium requirements.txt` and it should behave the same way.

Hope this helps :) If not, it would be helpful for me to know how you've configured and currently run it.

**Comment by inkhey** [comment]
Hello, Thanks for your answers. 
I'm using skjold as pre-commit with configuration set in `pyproject.toml`
in a similar way as example:
https://github.com/twu/skjold#configuration

```
[tool.skjold]
report-only = true
report-format = 'json'
sources = ["gemnasium"]
```

Thanks for your suggestion, i have not think of command line parameters. These does work as expected. I can find a workaround if needed, but i still cannot make these `pyproject.toml` work either from `skjold audit` or the suggested pre-commit:

```
  - repo: https://github.com/twu/skjold
    rev: v0.1.6
    hooks:
      - id: skjold
```

Another small point : I was expecting for some reason that "json" format as this is not "cli" value will return the output in a separated file, it's not really a problem, but maybe something can be made to make this a bit more obvious for user.

**Comment by twu** [comment]
I just tried this setup with the configuration you supplied. `report_only` and `report_format` if specified via the `pyproject.toml` will get overridden by the CLI _defaults_ which is definitely a bug. It should only use defaults if no other configuration was found. I dealt with a similar issue in another `click` project recently so I might have fix at hand already. Until there one though `report-only` and `report-format` specified in a `pyproject.toml` will not work at all. Sorry for that.

To get this working anyway one possible workaround would be to adjust your `.pre-commit-config.yaml` as shown below. Using `verbose`[[0](https://pre-commit.com/#creating-new-hooks)] will tell `pre-commit` (`1.6.0+`) to print the output despite `skjold` exiting _normally_ because of the `--report-only` flag. You could also specify the `-o json` there but it looks like this is not what you expected it to do anyway.

_.pre-commit-config.yaml_
```yaml
repos:
  - repo: https://github.com/twu/skjold
    rev: v0.1.6
    hooks:
    - id: skjold
      entry: skjold audit --report-only
      verbose: true
```

It also looks like there are two typos in the `README.md`. The _corrected_ section of the `pyproject.toml` should use underscores instead of dashes. However due to the bug above this currently won't make a difference, IMHO.

```toml
[tool.skjold]
report_only = true
report_format = 'json'
sources = ["gemnasium"]
```

> I was expecting for some reason that "json" format as this is not "cli" value will return the output in a separated file, it's not really a problem, but maybe something can be made to make this a bit more obvious for user.

You are right, `report_format` might suggest that it writes a report somewhere. `output_format` would've probably been a better choice. I'll try to fix it either by renaming the option or by providing the option to specify a file the _report_ is written to.

I'm currently a little busy with work but I'll try to fix these issues by the end of the month at the latest. If you need any further help with getting it to work just let me know :)

Thanks again :)
